import { IHerramienta, IHerramientasGenerales } from "../interfaces/IHerramienta";

const herramientas: IHerramientasGenerales = {
  T00TRLNR: {
    herramientas: <IHerramienta[]>[
      {
        descripcion: "Llave mixta 10mm",
        nroParte: "PT-004",
        nroSerie: "SR-01004",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Llave mixta 12mm",
        nroParte: "PT-006",
        nroSerie: "SR-01006",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Llave mixta 14mm",
        nroParte: "PT-008",
        nroSerie: "SR-01008",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Llave mixta 17mm",
        nroParte: "PT-011",
        nroSerie: "SR-01011",
        tecnicoActual: "Arroyo Mendoza Pedro",
        disponible: "5 de 5",
      },
      {
        descripcion: "Llave mixta 19mm",
        nroParte: "PT-013",
        nroSerie: "SR-01013",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Llave mixta 22mm",
        nroParte: "PT-016",
        nroSerie: "SR-01016",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Llave mixta 24mm",
        nroParte: "PT-018",
        nroSerie: "SR-01018",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Juego de llaves allen (Mm)",
        nroParte: "PT-097",
        nroSerie: "SR-01097",
        tecnicoActual: "Castro Agüero Sebastián",
        disponible: "5 de 6",
      },
      {
        descripcion: "Alicate",
        nroParte: "AL-001",
        nroSerie: "ALA23B009",
        tecnicoActual: "",
        disponible: "3 de 3",
      },
      {
        descripcion: "Alicate presión",
        nroParte: "PT-064",
        nroSerie: "SR-01064",
        tecnicoActual: "",
        disponible: "4 de 4",
      },
      {
        descripcion: "Alicate de corte",
        nroParte: "PT-067",
        nroSerie: "SR-01067",
        tecnicoActual: "",
        disponible: "4 de 4",
      },
      {
        descripcion: "Destornillador de golpe Punta Plana 3/8' x 10'",
        nroParte: "DGPP-010-004",
        nroSerie: "DGPP23B012",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Multímetro digital",
        nroParte: "PT-106",
        nroSerie: "SR-01106",
        tecnicoActual: "",
        disponible: "6 de 6",
      },
      {
        descripcion: "Dado 11 mm hexagonal",
        nroParte: "PT-042",
        nroSerie: "SR-01042",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Dado 12 mm hexagonal",
        nroParte: "PT-043",
        nroSerie: "SR-01043",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Dado 13 mm hexagonal",
        nroParte: "PT-044",
        nroSerie: "SR-01044",
        tecnicoActual: "Villanueva Baldeon Vicor",
        disponible: "4 de 5",
      },
      {
        descripcion: "Dado 14 mm hexagonal",
        nroParte: "PT-045",
        nroSerie: "SR-01045",
        tecnicoActual: "Villanueva Baldeon Vicor",
        disponible: "4 de 5",
      },
      {
        descripcion: "Dado 15 mm hexagonal",
        nroParte: "PT-046",
        nroSerie: "SR-01046",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Dado 16 mm hexagonal",
        nroParte: "PT-047",
        nroSerie: "SR-01047",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Dado 17 mm hexagonal",
        nroParte: "PT-048",
        nroSerie: "SR-01048",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Dado 18 mm hexagonal",
        nroParte: "PT-049",
        nroSerie: "R-01049",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Dado 19 mm hexagonal",
        nroParte: "PT-050",
        nroSerie: "SR-01050",
        tecnicoActual: "",
        disponible: "5 de 5",
      },
      {
        descripcion: "Saca filtro 3 1/2",
        nroParte: "DH-17-012",
        nroSerie: "DH17A23B020",
        tecnicoActual: "",
        disponible: "4 de 4",
      },
      {
        descripcion: "Bandeja",
        nroParte: "BD-016",
        nroSerie: "BDA23B024",
        tecnicoActual: "",
        disponible: "7 de 7",
      },
    ],
  },
  T00TR3M6: {
    herramientas: <IHerramienta[]>[],
  },
  T00TRTFD: {
    herramientas: <IHerramienta[]>[],
  },
};

export default herramientas;
